"""Per-language build artifact, test, and lint rules.

AutoShip's ``clean`` command has always formatted source files of many
languages (see :data:`clean._SOURCE_EXTENSIONS`). This module also performs
**language-aware artifact removal**: ``autoship clean artifacts`` walks the
project, detects the project type via
:func:`utils.project_detector.detect_project_type`, and removes the
language-native build outputs that this project's toolchain produces.

The rules are intentionally conservative — only directories and globs that
are unambiguously regenerable from source are listed. ``target/`` for Rust
is excluded wholesale because ``cargo`` uses it as a cache (see the
``rust-ship`` example plugin for the narrower ``target/debug`` /
``target/release`` split); ``node_modules/`` is never touched because it
is an install artifact, not a build output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class LanguageRule:
    """Build-artifact, test, and lint rules for a single language.

    Fields are plain lists of patterns (not compiled globs) so the rule
    table can be displayed verbatim in docs and CLI output without escaping
    concerns.
    """

    language: str
    """Human-readable language name (``"go"``, ``"rust"``, …)."""

    manifests: tuple[str, ...]
    """Files that mark a project as this language (``go.mod``, ``Cargo.toml``, …).
    Used to decide whether the rule applies to the current project."""

    artifact_dirs: tuple[str, ...] = ()
    """Directories that are safe to delete because they are pure build outputs."""

    artifact_globs: tuple[str, ...] = ()
    """Filename globs (matched against the basename) for loose build outputs
    (e.g. ``*.class``, ``*.tsbuildinfo``)."""

    test_command: str = ""
    """Suggested test command (printed by ``verify --suggest`` when the
    project language matches)."""

    lint_command: str = ""
    """Suggested linter command."""

    notes: str = ""
    """Free-form caveat printed alongside the rule (e.g. 'cargo cache is NOT
    removed wholesale')."""


# Order matters: when multiple manifests coexist (e.g. a Python project with
# a Node front-end), the first match wins for the *primary* language hint.
# ``clean artifacts`` always considers ALL matching rules, not just the
# primary one, so a polyglot repo gets cleaned for every detected language.
RULES: dict[str, LanguageRule] = {
    "python": LanguageRule(
        language="python",
        manifests=("pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"),
        # __pycache__ directories appear at every package level; we list the
        # top-level one here and rely on ``artifact_globs`` to sweep nested
        # ones via rglob. ``build`` and ``dist`` are setuptools/wheel outputs.
        artifact_dirs=("build", "dist", "eggs", ".eggs"),
        artifact_globs=("__pycache__", "*.pyc", "*.pyo", "*.egg-info"),
        test_command="pytest",
        lint_command="ruff check .",
        notes="__pycache__/ and *.pyc are bytecode caches regenerated on the "
        "next import. build/ and dist/ are setuptools/wheel outputs. "
        "*.egg-info/ is package metadata regenerated by ``pip install -e .``. "
        ".venv/ and venv/ are never removed (they are install artifacts, not "
        "build outputs).",
    ),
    "go": LanguageRule(
        language="go",
        manifests=("go.mod",),
        artifact_dirs=("bin",),
        artifact_globs=("*.test", "*.out"),
        test_command="go test ./...",
        lint_command="golangci-lint run",
        notes="The 'bin/' directory is the conventional go build output. "
        "*.test and *.out are compiled test binaries left by `go test -c`.",
    ),
    "rust": LanguageRule(
        language="rust",
        manifests=("Cargo.toml",),
        # target/ is intentionally NOT listed wholesale — cargo uses it as a
        # dependency cache. The rust-ship example plugin demonstrates the
        # narrower target/{debug,release} split for teams that want it.
        artifact_dirs=(),
        artifact_globs=(),
        test_command="cargo test",
        lint_command="cargo clippy -- -D warnings",
        notes="target/ is cargo's cache and is NOT removed by default. "
        "Use the rust-ship plugin pack to opt into target/{debug,release} cleanup.",
    ),
    "node": LanguageRule(
        language="node",
        manifests=("package.json",),
        artifact_dirs=("dist", "build", ".cache", "coverage"),
        artifact_globs=("*.tsbuildinfo",),
        test_command="npm test",
        lint_command="npm run lint",
        notes="node_modules/ is an install artifact, not a build output, and "
        "is never removed by AutoShip. dist/ and build/ are bundler outputs.",
    ),
    "java": LanguageRule(
        language="java",
        manifests=("pom.xml", "build.gradle", "build.gradle.kts"),
        artifact_dirs=("target/classes", "target/test-classes", "bin"),
        artifact_globs=("*.class",),
        test_command="mvn test",
        lint_command="mvn checkstyle:check",
        notes="Removes Maven's target/classes and target/test-classes. "
        "target/ as a whole is preserved because Maven stores site reports "
        "and dependency JARs there. Loose *.class files outside target/ "
        "are also swept.",
    ),
}


def rules_for_project(project_root: Path) -> list[LanguageRule]:
    """Return every language rule whose manifests are present in ``project_root``.

    A polyglot repo (e.g. Python back-end + Node front-end) returns both
    rules. Order follows :data:`RULES` insertion order, which is the same
    order the docs present the rules.
    """
    matches: list[LanguageRule] = []
    for rule in RULES.values():
        if any((project_root / manifest).exists() for manifest in rule.manifests):
            matches.append(rule)
    return matches


def primary_language(project_root: Path) -> str | None:
    """Return the language of the first matching rule, or None.

    Used by ``verify --suggest`` and the TUI dashboard to label the project
    with a single primary language. ``rules_for_project`` is the right call
    when callers care about every detected language.
    """
    matches = rules_for_project(project_root)
    return matches[0].language if matches else None


@dataclass
class ArtifactRemovalPlan:
    """Result of :func:`plan_artifact_removal`: files/dirs that would be removed."""

    by_language: dict[str, list[Path]] = field(default_factory=dict[str, list[Path]])
    skipped: list[Path] = field(default_factory=list[Path])

    @property
    def total(self) -> int:
        return sum(len(paths) for paths in self.by_language.values())


def plan_artifact_removal(
    project_root: Path,
    *,
    include_dirs: bool = True,
    include_globs: bool = True,
) -> ArtifactRemovalPlan:
    """Compute the set of paths ``clean artifacts`` would remove.

    The plan is a pure function of the on-disk state — it does not delete
    anything. Callers (the CLI command, tests, the TUI dashboard) iterate
    ``plan.by_language`` to display what would be removed and then call
    :func:`apply_artifact_removal` to execute the deletion.

    Args:
        project_root: Root to scan.
        include_dirs: When True, plan removal of directories listed in each
            matching rule's ``artifact_dirs``.
        include_globs: When True, plan removal of files matching each rule's
            ``artifact_globs`` (basename match, recursive).

    Returns:
        An :class:`ArtifactRemovalPlan`. ``skipped`` lists paths that exist
        but resolve outside ``project_root`` (defence against symlinks).
    """
    plan = ArtifactRemovalPlan()
    resolved_root = project_root.resolve()

    for rule in rules_for_project(project_root):
        bucket = plan.by_language.setdefault(rule.language, [])

        if include_dirs:
            for dirname in rule.artifact_dirs:
                candidate = (project_root / dirname).resolve()
                try:
                    inside = candidate.is_relative_to(resolved_root)
                except (OSError, ValueError, RuntimeError):
                    inside = False
                if not inside:
                    if candidate.exists():
                        plan.skipped.append(candidate)
                    continue
                if candidate.exists():
                    bucket.append(candidate)

        if include_globs:
            for pattern in rule.artifact_globs:
                # rglob accepts a glob pattern; for `*.class` it matches
                # basenames at any depth. Directory-name globs (e.g.
                # ``__pycache__``) also match at any depth, so we collect
                # both files and directories here so Python support works.
                for match in project_root.rglob(pattern):
                    resolved = match.resolve()
                    try:
                        inside = resolved.is_relative_to(resolved_root)
                    except (OSError, ValueError, RuntimeError):
                        inside = False
                    if not inside:
                        plan.skipped.append(resolved)
                        continue
                    # Don't descend into well-known dependency / install dirs.
                    if any(
                        part in {"node_modules", ".venv", "venv", ".git", "target"}
                        for part in match.parts
                    ):
                        continue
                    if match.is_file() or match.is_dir():
                        bucket.append(match)

    return plan


def apply_artifact_removal(plan: ArtifactRemovalPlan, *, dry_run: bool = False) -> int:
    """Execute an :class:`ArtifactRemovalPlan` and return the count removed.

    Directories are removed recursively; files are unlinked. Missing paths
    (already removed between plan and apply) are silently skipped — the
    plan is a snapshot, not a lock.

    When ``dry_run`` is True, no filesystem mutations happen and the return
    value reflects what *would* have been removed.
    """
    import shutil

    removed = 0
    for paths in plan.by_language.values():
        for path in paths:
            if dry_run:
                removed += 1
                continue
            try:
                if path.is_dir():
                    shutil.rmtree(path)
                    removed += 1
                elif path.is_file():
                    path.unlink()
                    removed += 1
            except OSError:
                continue
    return removed
